env:
  # Telegram
  TG_CHAT: "@dump_rom_bot"
  TG_TOKEN: ENCRYPTED[d1a9423df240b4603cb01c74226ce778d706ea74b0e392a648427279d2b1769c89ff6cb40d8d4010ac825ae2139258e4]
  
  # Gitlab
  PUSH_TO_GITLAB: true
  GITLAB_GROUP: RomdumprX
  GITLAB_TOKEN: ENCRYPTED[31be84f4bfbeaf35c538145a7e286f3ce79640884f789448a4c3e5dd3707aab05495855046462e92d33469729b99ec5b]
  GITLAB_INSTANCE: www.opencode.net
  
  # Private SSH Key
  PRIV_SSH_KEY: ENCRYPTED[61547963dc91785a65fb2d75f3404249971daffd79254d411fbb488de70fb17b2f42285e58ea5aa750228b7c95422c1e]
  # Public SSH Key 
  PUB_SSH_KEY: ENCRYPTED[698f72a178ba877476a0bec99c846640c321034f2c5051f62b755b6eb9ca8f13371de1befce18250eb16cab33b62d165]
  

task:
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'RomdumprX'
  skip: $CIRRUS_BRANCH == 'main'
  
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      privileged: true
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa $GITLAB_INSTANCE >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa
      - echo "$PUB_SSH_KEY" > ~/.ssh/id_rsa.pub
      

  Setup_script:
      - git config --global user.name "ajaysinghsati"
      - git config --global user.email "ajaysinghsati@gmail.com"
      - cd DumprX
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - echo "$GITLAB_INSTANCE" > .gitlab_instance
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt)

      

  
