task:
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'RomdumprX'
  
  auto_cancellation: $CIRRUS_BRANCH == 'autocancel'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch

      privileged: true
      cpu: 4
      memory: 16G


  Clone_script:
     - git clone https://github.com/ajaysinghsati/devicetree.git device/qti/holi
     - git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
     - git clone https://github.com/LineageOS/android_prebuilts_extract-tools prebuilts/extract-tools
     - git clone https://gitlab.com/android-dump/qti/holi.git
     - cd ~ 
     - ls
     - cd device 
     - ls
     - cd qti 
     - ls
     - cd holi
     - ls
      
     - ./setup-makefile.sh
     - ./extract-files.sh ~/holi
     
  

  Setup_script:
      - git config --global user.name "ajaysinghsati"
      - git config --global user.email "ajaysinghsati@gmail.com"
      
  
  Set-SSH-Keys_script:
      - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      
      
      - chmod 600 ~/.ssh/id_rsa
      - cd ~/.ssh 
      - cat id_rsa.pub
      
      
      
  Push-to-gitlab_script:

      - sleep 300 && echo "10 minutes have passed"
      - cd ~
      - cd holi
      - cd dummy-device-tree 
      - cd oneplus 
      
      - cd CPH2381
      
      - ls
   
      - git init 
     
      
      - git remote add origin git@github.com:ajaysinghsati/devicetree.git
      - git add .
      - git commit -m "Initial commit"
      - git push -u origin master
       

  
