
task:
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'RomdumprX'
  
  
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      privileged: true
      cpu: 4
      memory: 16G

  Clone_script:
     - git clone https://github.com/sebaubuntu-python/aospdtgen.git
     - cd aospdtgen 
     - pip3 install .
     - cd 
     - git clone https://www.opencode.net/Neil-Firmware-Dumps/qti/holi.git
  
  

  Setup_script:
      - git config --global user.name "ajaysinghsati"
      - git config --global user.email "ajaysinghsati@gmail.com"
      - cd holi 
      - ls 
      - cd 
      - python3 -m aospdtgen  [-o OUTPUT] holi
      
      - 

  DumprX_script:
      - cd dumpyara || echo "Already in the Directory"
      - ./dumpyara.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt)
  Set-SSH-Keys_script:
      - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa www.opencode.net >> ~/.ssh/known_hosts
      
      
      - chmod 600 ~/.ssh/id_rsa
      - cd ~/.ssh 
      - cat id_rsa.pub
      - cd -
      - ls
      
  Push-to-gitlab_script:

      - sleep 300 && echo "10 minutes have passed"
      - cd 
      - cd dumpyara 
      - cd out 
      - ls
     
   
      - git init 
     
      
      - git remote add origin git@www.opencode.net:ajaysinghsati/a.git
      - git add .
      - git commit -m "Initial commit"
      - git push -u origin master
       

  
